# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6-7eAYLpxENdtCmQE81EPoJ70gpzDDc
"""

from typing import Union
#creating a list
age_list=[24,25,26,27,28]
#insert
age_list.insert(2,30)
#pop
age_list.pop(-1)
#extend
age_list.extend([29,30,26])
#sort
age_list.sort(reverse=True)
#max,min,sum of age-list
print(max(age_list))
print(min(age_list))
print(sum(age_list))
#print
print(age_list)
#type
print(type(age_list))
#creating a sring list
name_list=["sai","vikram","maithili","sanjana","aashrith"]
#append
name_list.append("yazini")
#remove
name_list.remove("yazini")
#first eliment
print(name_list[0])
#last eliment
print(name_list[-1])
#2,4 index
print(name_list[2:4])
#reverse
print(name_list[::-1])
#print
print(name_list)
#dictionary
student_marks={"sai":100,"vikram":90,"maithili":80,"sanjana":70,"aashrith":60}
#access and print
print(f"Mark of Sai: {student_marks['sai']}")
#add janani
student_marks["janani"]=80
#update
student_marks["sai"]=82
#keys,valuesand items
print(student_marks.keys())
print(student_marks.values())
print(student_marks.items())
print(student_marks)
print(type(student_marks))
#set
my_set={'a','e','i','o','u','a','a','i'}
#type
print(type(my_set))
#changing the value of 4th
#cant change because sets are unordered we cant change them by using indexing
#print
print(my_set)
#creating 2 sets
i={1, 3, 5, 7, 9}
j={2, 3, 5, 8, 10}
#performing union and intersection
union_result = i.union(j)
intersection_result = i.intersection(j)
#print
print(union_result)
print(intersection_result)
#operaters and conditional statements
score=int(input("enter the score (1-10): "))
#IF
if score > 7:
  print("above average, good keep it up")
elif score > 4:
  print("average,try harder")
else:
  print("below average, need to improve")
print(score)